### ISSUE TITLE
NonBlockingHashMapLong#putIfAbsent() is non-atomic for key 0

### ISSUE THREAD

**Issue by vyazelenko** [stephenc/high-scale-lib#5]
Using `NonBlockingHashMapLong` in a code that models atomic operation using `get()` and `putIfAbsent()` methods **does not** work (i.e. non-atomic) for key `0`. The code in questions looks like this:

``` java
String value = map.get(0);
if (value == null) {
  value = newValue;
  String tmp = map.putIfAbsent(0, value);
  if (tmp != null) {
    return tmp;
  }
}
return value;
```

The idea is that only thread should ever set the value for key `0`. However in reality this code will return more than one value, i.e. more than thread will insert it's value into the map.

I have created standalone test [NonBlockingHashMapLongZeroKeyConcurrentGetPutIfAbsentTest](https://github.com/vyazelenko/high-scale-lib/blob/key-zero-bug/high-scale-lib/src/test/java/org/cliffc/high_scale_lib/non_blocking_hashmap/NonBlockingHashMapLongZeroKeyConcurrentGetPutIfAbsentTest.java) to reproduce the problem. It fails on both JDK 7 and JDK 8 on Mac OS X and Windows 7 environments. Further more the test fails on both [high-scale-lib-1.1.4.jar](http://mvnrepository.com/artifact/com.github.stephenc.high-scale-lib/high-scale-lib/1.1.4) and original [high-scale-lib-v1.1.2.zip](http://downloads.sourceforge.net/project/high-scale-lib/high-scale-lib/high-scale-lib-v1.1.2.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fhigh-scale-lib%2F%3Fsource%3Dtyp_redirect&ts=1416606677&use_mirror=garr) from [Highly Scalable Java](http://sourceforge.net/projects/high-scale-lib/).

**Comment by vyazelenko** [comment]
@cliffclick Is (http://sourceforge.net/projects/high-scale-lib/) still alive? Or should bugs such as this one be reported against clones?
Can you have a look at this issue, please?

**Comment by vyazelenko** [comment]
[NonBlockingHashMapLongZeroKeyConcurrentGetPutIfAbsentTest](https://github.com/vyazelenko/high-scale-lib/blob/key-zero-bug/high-scale-lib/src/test/java/org/cliffc/high_scale_lib/non_blocking_hashmap/NonBlockingHashMapLongZeroKeyConcurrentGetPutIfAbsentTest.java) has 2 tests:
- `test_empty_map_key_0()` - always fails, uses `0` as key

```
junit.framework.AssertionFailedError: [worker #4, worker #1] 
Expected :1
Actual   :2
```
- `test_empty_map_key_123()`\- always passes, uses `123` as key

**Comment by vyazelenko** [comment]
The problem seems to be in the `NonBlockingHashMapLong#putIfMatch(long, Object, Object)` method lines 306-314:

``` java
    if( key == NO_KEY ) {
      final Object curVal = _val_1;
      if( oldVal == NO_MATCH_OLD || // Do we care about expected-Value at all?
          curVal == oldVal ||       // No instant match already?
          (oldVal == MATCH_ANY && curVal != TOMBSTONE) ||
          oldVal.equals(curVal) )   // Expensive equals check
        CAS(_val_1_offset,curVal,newVal); // One shot CAS update attempt
      return curVal == TOMBSTONE ? null : (TypeV)curVal; // Return the last value present
    }
```

Here more than thread will read initial value of the **_val_1** field. Because initial value is `TOMBSTONE` it satisfies if condition (i.e. `curVal == oldVal`) and threads will race to perform a CAS. However only one thread will succeed in CAS and put it's value into **_val_1** field. But **all those threads** that raced to perform a CAS will return `null` from `putIfMatch` method, because condition `curVal == TOMBSTONE` is **true**.

This violates `putIfAbsent` atomicity contract that must guarantee that method returns `null` **if-and-only-if** value was put into the map.

**Comment by cliffclick** [comment]
Code is fixed in my local repo for some time now - 

```
if( key == NO_KEY ) {
  Object curVal = _val_1;
  if( oldVal == NO_MATCH_OLD || // Do we care about expected-Value at all?
      curVal == oldVal ||       // No instant match already?
      (oldVal == MATCH_ANY && curVal != TOMBSTONE) ||
      oldVal.equals(curVal) ) { // Expensive equals check
    if( !CAS(_val_1_offset,curVal,newVal) ) // One shot CAS update attempt
      curVal = _val_1;                      // Failed; get failing witness
  }
  return curVal == TOMBSTONE ? null : (TypeV)curVal; // Return the last value present
}
```

**Comment by cliffclick** [comment]
fyi - i haven't look on the SF code in awhile.  Been hacking on https://github.com/0xdata/h2o-dev

**Comment by cliffclick** [comment]
(which has a copy of the NonBlockingHashMap utilities I've hacked on some)

**Comment by vyazelenko** [comment]
Thanks @cliffclick , I'll checkout (https://github.com/0xdata/h2o-dev) repo and see whether it fixes my problem.

**Comment by vyazelenko** [comment]
Great! Latest version of (https://github.com/0xdata/h2o-dev/blob/master/h2o-core/src/main/java/water/nbhm/NonBlockingHashMapLong.java) passes the tests. I'll switch to that version in my projects now instead of SF version or other clones of it.

**Comment by vyazelenko** [comment]
@cliffclick I've created a pull request https://github.com/0xdata/h2o-dev/pull/12 with the test case in question. Maybe it is useful as a safety net to have. ;)

**Comment by cliffclick** [comment]
On 11/22/2014 11:32 AM, Dmitry Vyazelenko wrote:

> @cliffclick https://github.com/cliffclick I've created a pull 
> request 0xdata/h2o-dev#12 https://github.com/0xdata/h2o-dev/pull/12 
> with the test case in question. Maybe it is useful as a safety net to 
> have. ;)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/stephenc/high-scale-lib/issues/5#issuecomment-64092322.
> 
> pulled

THanks
CLiff
